"""
AST-Based Safety Validator for LLM-Generated Test Code

Validates pytest test functions generated by LLM before execution.
Uses AST analysis to enforce:
- Import allowlist (only safe testing libraries)
- Forbidden function calls (os.system, subprocess.*, eval, exec, etc.)
- No file writes outside expected test behavior

This is the safety gate between LLM-generated code and test execution.
"""
import ast
import logging
from typing import Optional


# Allowed top-level modules for import
ALLOWED_MODULES = {
    # Testing
    "pytest",
    # HTTP/Network
    "requests", "urllib", "urllib.parse", "http", "http.client",
    # SSH
    "paramiko",
    # MQTT
    "paho", "paho.mqtt", "paho.mqtt.client",
    # CoAP
    "aiocoap",
    # Modbus
    "pymodbus", "pymodbus.client",
    # Low-level networking
    "socket", "ssl", "struct",
    # Utilities
    "time", "json", "base64", "hashlib", "hmac",
    "binascii", "codecs", "re", "io",
    # Async support
    "asyncio",
    # Type hints
    "typing",
}

# Dangerous function names (fully-qualified and bare)
DANGEROUS_CALLS = {
    # OS-level execution
    "os.system", "os.popen", "os.exec", "os.execl", "os.execle",
    "os.execlp", "os.execv", "os.execve", "os.execvp", "os.execvpe",
    "os.spawn", "os.spawnl", "os.spawnle", "os.spawnlp",
    # Subprocess
    "subprocess.run", "subprocess.call", "subprocess.check_call",
    "subprocess.check_output", "subprocess.Popen", "subprocess.getoutput",
    "subprocess.getstatusoutput",
    # Dynamic code execution
    "eval", "exec", "compile", "execfile",
    # Import manipulation
    "__import__", "importlib.import_module",
    # File operations (write/delete)
    "os.remove", "os.unlink", "os.rmdir", "os.removedirs",
    "shutil.rmtree", "shutil.move",
}

# Dangerous modules that should never be imported
FORBIDDEN_MODULES = {
    "os", "subprocess", "shutil", "sys", "ctypes",
    "importlib", "code", "codeop", "compileall",
    "multiprocessing", "threading",
    "signal", "resource", "pty", "fcntl",
    "tempfile",  # Could be used for file creation
}


def _get_module_root(module_name: str) -> str:
    """Extract the root module from a dotted module path."""
    return module_name.split(".")[0] if module_name else ""


def _is_allowed_module(module_name: str) -> bool:
    """Check if a module is in the allowlist."""
    if not module_name:
        return False
    root = _get_module_root(module_name)
    if root in FORBIDDEN_MODULES:
        return False
    # Check if the full path or root is allowed
    return module_name in ALLOWED_MODULES or root in {
        _get_module_root(m) for m in ALLOWED_MODULES
    }


def _get_call_name(node: ast.Call) -> Optional[str]:
    """Extract the fully-qualified function name from a Call node."""
    if isinstance(node.func, ast.Name):
        return node.func.id
    elif isinstance(node.func, ast.Attribute):
        parts = []
        current = node.func
        while isinstance(current, ast.Attribute):
            parts.append(current.attr)
            current = current.value
        if isinstance(current, ast.Name):
            parts.append(current.id)
        return ".".join(reversed(parts))
    return None


def validate_generated_test(code: str) -> tuple[bool, list[str]]:
    """Validate LLM-generated pytest code via AST analysis.

    Checks:
    1. Valid Python syntax
    2. Only allowed imports
    3. No dangerous function calls
    4. No file write operations
    5. Contains at least one test function

    Args:
        code: Python source code string.

    Returns:
        Tuple of (is_valid, list_of_violations).
        is_valid is True if code passes all checks.
    """
    violations = []

    # 1. Parse the AST
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return False, [f"Syntax error at line {e.lineno}: {e.msg}"]

    has_test_function = False

    for node in ast.walk(tree):
        # 2. Check imports
        if isinstance(node, ast.Import):
            for alias in node.names:
                if not _is_allowed_module(alias.name):
                    violations.append(
                        f"Forbidden import: '{alias.name}' "
                        f"(line {node.lineno})"
                    )

        elif isinstance(node, ast.ImportFrom):
            if node.module and not _is_allowed_module(node.module):
                violations.append(
                    f"Forbidden import from: '{node.module}' "
                    f"(line {node.lineno})"
                )

        # 3. Check function calls
        elif isinstance(node, ast.Call):
            call_name = _get_call_name(node)
            if call_name:
                # Check direct match
                if call_name in DANGEROUS_CALLS:
                    violations.append(
                        f"Forbidden call: '{call_name}' "
                        f"(line {node.lineno})"
                    )
                # Check partial matches for module patterns
                for dangerous in DANGEROUS_CALLS:
                    root = dangerous.split(".")[0]
                    if call_name.startswith(root + ".") and root in FORBIDDEN_MODULES:
                        violations.append(
                            f"Forbidden call pattern: '{call_name}' "
                            f"(matches {dangerous}, line {node.lineno})"
                        )
                        break

                # Check for open() with write modes
                if call_name == "open" and len(node.args) >= 2:
                    mode_arg = node.args[1]
                    if isinstance(mode_arg, ast.Constant) and isinstance(mode_arg.value, str):
                        if any(c in mode_arg.value for c in ("w", "a", "x")):
                            violations.append(
                                f"File write via open() with mode '{mode_arg.value}' "
                                f"(line {node.lineno})"
                            )

        # 4. Check for test functions
        elif isinstance(node, ast.FunctionDef):
            if node.name.startswith("test_"):
                has_test_function = True

    # 5. Must contain at least one test function
    if not has_test_function:
        violations.append("No test function found (must start with 'test_')")

    is_valid = len(violations) == 0
    if not is_valid:
        logging.warning(
            f"[LLMValidator] Code validation failed with {len(violations)} violations: "
            f"{violations[:3]}{'...' if len(violations) > 3 else ''}"
        )

    return is_valid, violations


def validate_multiple_tests(tests: list[dict]) -> list[dict]:
    """Validate a list of LLM-generated test dicts.

    Each dict should have a 'pytest_code' field.

    Returns:
        List of dicts with added 'valid' (bool) and 'violations' (list) fields.
        Only valid tests are included in the returned list.
    """
    validated = []
    for test in tests:
        code = test.get("pytest_code", "")
        if not code:
            test["valid"] = False
            test["violations"] = ["No pytest_code field"]
            continue

        is_valid, violations = validate_generated_test(code)
        test["valid"] = is_valid
        test["violations"] = violations

        if is_valid:
            validated.append(test)
        else:
            logging.info(
                f"[LLMValidator] Rejected test '{test.get('test_id', '?')}': "
                f"{violations[:2]}"
            )

    logging.info(
        f"[LLMValidator] Validated {len(validated)}/{len(tests)} tests passed"
    )
    return validated
